version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    install:
      # upgrade pip for --group support
      - pip install --upgrade pip
      # install geedim with docs dependency group
      - pip install --group docs .
