# Test publishing to, and installing and running with Test PyPI

name: Install & test PyPI package
on:
  workflow_dispatch:

jobs:
  # Install geedim from Test PyPI and test CLI
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: ['3.11', '3.13']
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install geedim from PyPI
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade geedim
      - name: Test geedim CLI
        timeout-minutes: 5
        env:
          EE_SERVICE_ACC_PRIVATE_KEY: ${{ secrets.EE_SERVICE_ACC_PRIVATE_KEY }}
        shell: bash
        run: |
          geedim --version
          geedim --help
          geedim search --help
          geedim search -c l8-c2-l2 -s 2019-02-01 -e 2019-03-01 --bbox 23 -33 23.2 -33.2 composite -cm q-mosaic --mask download --scale 30 --crs EPSG:3857 -o
          dir LANDSAT-LC08-C02-T1_L2-2019_02_04-2019_02_20-Q-MOSAIC-COMP.tif && echo "Test OK"
          pwd
          ls -R
