name: Build & publish to Test PyPI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build package
        run: python -m build

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      id-token: write  # required for trusted publishing
    environment:
      name: pypi
      url: https://test.pypi.org/p/geedim

    steps:
      - name: Retrieve distribution
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish distribution
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
