# Test publishing to, and installing and running with Test PyPI

name: Build & publish to Test PyPI
on:
  workflow_dispatch:

jobs:
  # Build geedim package and upload to Test PyPI
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      - name: Build package
        run: python -m build
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        continue-on-error: true
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
      - name: Clean up
        run: rm -Rf *

  # Install geedim from Test PyPI and test CLI
  test:
    needs: publish
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        python-version: ['3.12']
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install geedim from Test PyPI
        run: |
          python -m pip install --upgrade pip
          python -m pip install --extra-index-url https://test.pypi.org/simple/ --upgrade geedim
      - name: Test geedim CLI
        timeout-minutes: 5
        env:
          EE_SERVICE_ACC_PRIVATE_KEY: ${{ secrets.EE_SERVICE_ACC_PRIVATE_KEY }}
        run: |
          geedim --version
          geedim search -c l8-c2-l2 -s 2019-02-01 -e 2019-03-01 --bbox 23 -33 23.2 -33.2 composite -cm q-mosaic --mask download --scale 30 --crs EPSG:3857 -r - -o
          dir -f Q-MOSAIC-COMP.tif && echo "Test OK"
          pwd
          ls -R
